[[plugins]]
  package = "@netlify/plugin-nextjs"
[build]
  command = "next build"
  publish = ".next"
  base = "./web-app"
[dev]
  framework = "next"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200